#-------------------------------------------------------------------------
#              Touch Of Silk
#-------------------------------------------------------------------------
# Thank you all for downloading my plugin. If you all do enjoy it leave
# a 5 star review! If you all need any assistance feel free to fill out
# a issue on github or contact us on our discord!
# Discord Invite: https://discord.gg/PSZS7WnuG2
#---------------------------------------------------------------------------
# Plugin Permissions
#---------------------------------------------------------------------------
# tos.amethyst
# tos.*
#
#----------------------------------------------------------------------------
# Silk Touch Settings
#----------------------------------------------------------------------------
Silk-Touch-Spawners-Enabled: true
Silk-Touch-Budding-Amethyst-Enabled: true